# Generated by Django 5.1.4 on 2025-01-07 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_aboutfeature_details_aboutfeature_image_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutfeature',
            name='image_class',
        ),
        migrations.RemoveField(
            model_name='aboutfeature',
            name='is_featured',
        ),
    ]
