# Generated by Django 5.1.4 on 2025-01-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_remove_aboutfeature_image_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutfeature',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
