# Generated by Django 5.1.4 on 2025-01-07 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0004_alter_aboutfeature_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutFeature',
        ),
    ]
